### ISSUE TITLE
这个项目好像少了一个MenuList列表？

### ISSUE THREAD

**Issue by AlianOL** [AntJavascript/flutter-shop#1]
这个项目好像少了一个MenuList列表？，我运行的时候提示MenuListServe.dart文件少MenuList列表

**Comment by AntJavascript** [comment]
// import '../../model/MenuListServe.dart'; // 分类导航区域数据结构 
已经注释掉了呀，不需要那个文件的啊

**Comment by AntJavascript** [comment]
或者你删除掉MenuListServe.dart 这个文件
